import { writeFileSync } from "node:fs";
import { eachSwatch } from "../styles/palette.ts";

const lines = eachSwatch().map(({ name, oklch, hex }) => `  --color-${name}: ${oklch}; /* ${hex} */`);

const output = `/* Generated by scripts/generate-tokens.ts from styles/palette.ts. Do not edit by hand. */
@theme {
${lines.join("\n")}
}
`;

writeFileSync(new URL("../app/tokens.generated.css", import.meta.url), output);
console.log(`Wrote ${lines.length} primitive color tokens.`);
