-- Kanazawa schema.
--
-- Two tables rather than one, because the contact gate has to hold in the
-- database. Someone who opens devtools and queries with the anon key must not
-- be able to read an email address, so contact details live in their own table
-- behind a policy that requires the caller to have planted a pin of their own.
--
-- Coordinates are plain columns. The map reads every pin and filters in the
-- browser, so there is no spatial query yet and no reason to require PostGIS.

create table public.pins (
  id uuid primary key default gen_random_uuid (),
  -- The map payload is packed binary, where a 36-byte uuid per pin would dwarf
  -- the coordinates. seq is the identifier the map and its detail route use.
  seq bigint generated by default as identity unique,
  owner_id uuid not null unique references auth.users (id) on delete cascade,
  display_name text not null check (char_length(trim(display_name)) between 1 and 40),
  neighborhood text not null check (char_length(trim(neighborhood)) between 1 and 60),
  note text check (char_length(note) <= 180),
  lng double precision not null check (lng between -180 and 180),
  lat double precision not null check (lat between -90 and 90),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- The map read is ordered by recency, so the newest plant lands last.
create index pins_created_at_idx on public.pins (created_at);

create table public.pin_contacts (
  pin_id uuid primary key references public.pins (id) on delete cascade,
  owner_id uuid not null references auth.users (id) on delete cascade,
  email text check (char_length(email) <= 254),
  instagram text check (char_length(instagram) <= 30),
  website text check (char_length(website) <= 200)
);

alter table public.pins enable row level security;
alter table public.pin_contacts enable row level security;

-- Name, neighborhood and note are the public face of a pin.
create policy "pins are readable by anyone" on public.pins for
select
  using (true);

create policy "a person plants their own pin" on public.pins for insert to authenticated
with
  check (auth.uid () = owner_id);

create policy "a person edits their own pin" on public.pins
for update
  to authenticated using (auth.uid () = owner_id)
with
  check (auth.uid () = owner_id);

create policy "a person pulls up their own pin" on public.pins for delete to authenticated using (auth.uid () = owner_id);

-- The gate: contact details are readable only by someone who is on the map,
-- and always by the owner of the row.
create policy "contacts are readable by people who are on the map" on public.pin_contacts for
select
  to authenticated using (
    owner_id = auth.uid ()
    or exists (
      select
        1
      from
        public.pins
      where
        pins.owner_id = auth.uid ()
    )
  );

create policy "a person writes their own contact details" on public.pin_contacts for all to authenticated using (auth.uid () = owner_id)
with
  check (auth.uid () = owner_id);

create
or replace function public.touch_updated_at () returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger pins_touch_updated_at before
update on public.pins for each row
execute function public.touch_updated_at ();
