-- Gatherings.
--
-- Every study of community platforms says the same two things: people leave
-- because nothing brings them back, and the ones that last are the ones that
-- get members into the same room. A map of people is a directory you read
-- once. A map of people and the times they will be somewhere is a reason to
-- return.
--
-- Deliberately not an events platform. No RSVPs, no attendee lists, no
-- comments: one person says where they will be and when, and it disappears
-- afterwards. Anything more is a moderation surface nobody has staff for.
create table if not exists public.gatherings (
  id uuid primary key default gen_random_uuid (),
  seq bigint generated by default as identity unique,
  host_id uuid not null references auth.users (id) on delete cascade,
  title text not null check (char_length(trim(title)) between 1 and 80),
  place text not null check (char_length(trim(place)) between 1 and 80),
  note text check (char_length(note) <= 280),
  lng double precision not null check (lng between -180 and 180),
  lat double precision not null check (lat between -90 and 90),
  starts_at timestamptz not null,
  created_at timestamptz not null default now()
);

-- Read paths ask for what is still ahead, ordered by when it starts.
create index if not exists gatherings_upcoming_idx on public.gatherings (starts_at);

create index if not exists gatherings_host_idx on public.gatherings (host_id);

alter table public.gatherings enable row level security;

-- Visible to anyone signed in, which is everybody who can reach the map.
drop policy if exists "gatherings are readable by people on the map" on public.gatherings;

create policy "gatherings are readable by people on the map" on public.gatherings for
select
  to authenticated using (true);

drop policy if exists "a person posts their own gathering" on public.gatherings;

create policy "a person posts their own gathering" on public.gatherings for insert to authenticated
with
  check (auth.uid () = host_id);

drop policy if exists "a person edits their own gathering" on public.gatherings;

create policy "a person edits their own gathering" on public.gatherings
for update
  to authenticated using (auth.uid () = host_id)
with
  check (auth.uid () = host_id);

drop policy if exists "a person calls off their own gathering" on public.gatherings;

create policy "a person calls off their own gathering" on public.gatherings for delete to authenticated using (auth.uid () = host_id);

drop policy if exists "moderators remove a gathering" on public.gatherings;

create policy "moderators remove a gathering" on public.gatherings for delete to authenticated using (public.is_moderator ());

-- Somewhere to record that a digest went out, so nobody is mailed twice about
-- the same neighbours.
create table if not exists public.digest_sends (
  user_id uuid primary key references auth.users (id) on delete cascade,
  last_sent_at timestamptz not null default now(),
  last_pin_seq bigint not null default 0
);

alter table public.digest_sends enable row level security;

drop policy if exists "a person reads their own digest record" on public.digest_sends;

create policy "a person reads their own digest record" on public.digest_sends for
select
  to authenticated using (auth.uid () = user_id);
